version: "3.8"

services:
  #data collector service flask
  collector:
    build:
      context: ./collector
    container_name: data_collector
    # environment:
    #   DATABASE_URL: postgres://myuser:mypassword@database:5432/mydatabase
    # depends_on:
    #   - database
    ports:
      - "5000:5000"
    